#pragma once

//#define USE_I2C

//#undef RGBLED_NUM
//#define RGBLED_NUM 12
//#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_CHRISTMAS

#define TAPPING_TERM 175
#define TAPPING_TOGGLE 3

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

//#define RGBLIGHT_HUE_STEP 8
//#define RGBLIGHT_SAT_STEP 8
//#define RGBLIGHT_VAL_STEP 8

//#define ENCODER_DIRECTION_FLIP
//#define ENCODER_RESOLUTION 2
